[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Remi Stessens"]
description = "Rust WASM for Mayfair Tools!"
license = "MIT"
repository = "https://github.com/rust-lang/cargo"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
wasm-bindgen = "0.2"


