name: Deploy WASM to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (Nightly)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WebAssembly package
        run: wasm-pack build --target web --out-dir pkg

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload WASM build artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: wasm-build
          path: ./pkg
          if-no-files-found: error
          retention-days: 7
          compression-level: 6
          overwrite: true
          include-hidden-files: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: ./pkg

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
